### ISSUE TITLE
Problema al importar la estructura del la base de datos en phpmyadmin

### ISSUE THREAD

**Issue by Ed-Spain** [ioticos/ioticos_admin#1]
Estimados 
En primer lugar muchas gracias por vuestros video y vuestra magnifica contribuciuon a los que somos tan novatos en el mundo del 'iot'.

Siguiendo paso a paso vuestro video tutorial (youtube), cuando he importado la estructura de la Base de Datos SQL me ha saltado el siguiente error.

![error-phpadmin](https://user-images.githubusercontent.com/16515137/64127843-b91c7200-cdb3-11e9-8973-fb01be09d25a.jpg)

Saludos.

**Comment by ioticos** [comment]
Hola Ed, prueba ahora, hicimos algunas correcciones, y lo probamos en phpmyadmin y ya estaría funcionando ok, por favor tennos al tanto. Gracias!

**Comment by Ed-Spain** [comment]
Hola ,

Ahora sí ya lo hice funcionar. Muchas gracias!!!
Ahora a tratear un poco.... mientras colgais nuevos videos.
Saludos,
